name: Generate Pacman Contributions

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Pac-Man graph
        uses: Platane/snk@v3
        with:
          github_user_name: VishalGCode
          outputs: |
            ./output/pacman-contribution-graph.svg
            ./output/pacman-contribution-graph-dark.svg
    
      - name: Upload to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Generate Pac-Man contribution graph"
          add: "./output"
